### ISSUE TITLE
Quadratic solver without constant - problem?

### ISSUE THREAD

**Issue by smilingthax** [toastedcrumpets/stator#1]
https://github.com/toastedcrumpets/stator/blob/master/stator/symbolic/polynomial.hpp#L737

For the constant ==0 case only `-f[1]` is returned, whereas I'd expect `-f[1]/f[2]`, as the scaling to normalize the x^2 -coefficient to 1 comes only 3 lines later...

**Comment by toastedcrumpets** [comment]
Thanks for the spot! Clearly a typo. I've added a test case to make sure I don't break it in future.
